# Training params

read_from_file    : False
output_to_file    : True
data_path         : "data/robot_graphs/"
batch_size        : 256
epochs            : 10000
seed              : 42
log_interval      : 10
lr                : 1.0e-3
kl                : 0.2
bce               : 1.0e+1
gce               : 0.0
vce               : 0.0
reduction         : "sum"
bce_reduction     : "sum"
ce_reduction      : "sum"
